version: '3.8'

services:
  shopper-move-pg:
    image: bitnami/postgresql
    container_name: shopper-move-pg
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      POSTGRESQL_USERNAME: will
      POSTGRESQL_PASSWORD: 123456
      POSTGRESQL_DATABASE: shoppermove
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: dev
      JWT_SECRET: jwtsecretshoppermove
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DATABASE_URL: "postgresql://will:123456@shopper-move-pg:5432/shoppermove?schema=public"
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - shopper-move-pg

  client:
    build:
      context: ./client
      args:
        VITE_GOOGLE_API_KEY: ${GOOGLE_API_KEY}
        VITE_API_URL: "http://localhost:8080" 
    ports:
      - "8081:80"
    networks:
      - mynetwork
    depends_on:
      - api

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
